name: azureml_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.0.1
  - pip:
    # Core ML frameworks
    - tensorflow==2.15.0
    - torch==2.0.1
    - torchvision==0.15.2
    - torchaudio==2.0.2
    
    # Azure ML and related packages
    - azureml-core==1.53.0
    - azureml-dataset-runtime==1.53.0
    - azureml-defaults==1.53.0
    - azureml-telemetry==1.53.0
    - azureml-automl-core==1.53.0
    
    # Microsoft Olive for model optimization
    - olive-ai
    - optimum
    
    # ONNX Runtime for efficient inference
    - onnx
    - onnxruntime
    - onnxruntime-genai
    
    # Transformers and related libraries
    - transformers==4.36.2
    - tokenizers==0.15.0
    - peft
    - bitsandbytes
    
    # Utility packages
    - numpy==1.23.5
    - pandas==2.0.3
    - scikit-learn==1.3.0
    - matplotlib==3.7.2
    - python-dotenv==1.0.0
    
    # Notebook utilities
    - ipykernel==6.25.0
    - ipywidgets==8.0.7
    - jupyter==1.0.0
    
variables:
  AZUREML_SUBSCRIPTION_ID: ${AZUREML_SUBSCRIPTION_ID}
  AZUREML_RESOURCE_GROUP: ${AZUREML_RESOURCE_GROUP}
  AZUREML_WS_NAME: ${AZUREML_WS_NAME}
  TEACHER_MODEL_NAME: ${TEACHER_MODEL_NAME}
  TEACHER_MODEL_ENDPOINT: ${TEACHER_MODEL_ENDPOINT}
  TEACHER_MODEL_KEY: ${TEACHER_MODEL_KEY}
